[feat]:Add numeric sequence feature
alibaba/EasyRec pull request #102
Opened 2021-12-28 11:03 UTC by lgqfhwy

Add numeric operator: hash_bucks, num_buckets, boundary, raw for sequence feature.

2021-12-28 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/EasyRec?pullRequest=102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/EasyRec?pullRequest=102) before we can accept your contribution.<br/><hr/>**yancheng.lgq** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/EasyRec?pullRequest=102) it.</sub>

2022-01-04 06:14 UTC, chengmengli06 commented on easy_rec/python/input/input.py
> +              dense_shape=[sample_num, fc.sequence_length])
should it be 3 dimensional ?

2022-01-04 06:25 UTC, chengmengli06 requested changes

2022-01-04 06:25 UTC, chengmengli06 commented on easy_rec/python/feature_column/feature_column.py
>        self._deep_columns[feature_name] = fc
should it be placed in self._sequence_columns?

2022-01-05 02:29 UTC, lgqfhwy commented on easy_rec/python/input/input.py
> +              dense_shape=[sample_num, fc.sequence_length])
不是。目前输入的序列特征就是二维的，第一维是 batch_size, 第二维是 序列长度。

2022-01-11 02:18 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
>        self._deep_columns[feature_name] = fc
不是，这个地方我没有改动。这个地方应该是你写的。

2022-02-21 07:25 UTC, tiankongdeguiji commented on easy_rec/python/feature_column/feature_column.py
> +              config.sequence_length,
config.sequence_length -> config.raw_input_dim

2022-02-21 07:25 UTC, tiankongdeguiji commented on easy_rec/python/compat/feature_column/feature_column_v2.py
> +class SequenceRawColumn(
SequenceNumericColumn

2022-02-21 07:25 UTC, tiankongdeguiji commented on easy_rec/python/compat/feature_column/feature_column_v2.py
> +class SequenceIdentityCategoricalColumn(
dup with SequenceCategoricalColumn?

2022-02-25 08:20 UTC, lgqfhwy commented on easy_rec/python/compat/feature_column/feature_column_v2.py
> +class SequenceRawColumn(
已经改好了。

2022-02-25 09:29 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +              config.sequence_length,
已经改好了。

2022-02-25 09:43 UTC, lgqfhwy commented on easy_rec/python/compat/feature_column/sequence_feature_column.py
>    def transform_feature(self, transformation_cache, state_manager):
已经改好了。

2022-02-25 09:55 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +          tmp_id_col = sequence_feature_column.sequence_numeric_column_with_categorical_column_with_identity(
不能替换。我确认了一下，这个 sequence_categorical_column_with_identity 并不支持多维 (三维及以上的特征输入)，而sequence_numeric_column_with_categorical_column_with_identity 主要的改变就是在此基础上支持了三维及以上的输入。

2022-02-25 09:56 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +      fc = sequence_feature_column.sequence_numeric_column(
建立一个 sequence_numeric_column, 这个地方没有问题。

2022-02-26 08:07 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +          wgt_fc = sequence_feature_column.sequence_numeric_column_with_weighted_categorical_column(
我发现原来的 sequence column 就以 sequence_categorical_column_with 开头，我这个地方以 sequence_numeric_column_with 也是为了和其区分。

2022-02-28 05:52 UTC, tiankongdeguiji requested changes

2022-02-28 05:52 UTC, tiankongdeguiji commented on easy_rec/python/feature_column/feature_column.py
> +          tmp_id_col = sequence_feature_column.sequence_numeric_column_with_categorical_column_with_identity(
扩展sequence_categorical_column_with_identity支持三维及以上的特征输入

2022-02-28 05:52 UTC, tiankongdeguiji commented on easy_rec/python/feature_column/feature_column.py
> +          wgt_fc = sequence_feature_column.sequence_numeric_column_with_weighted_categorical_column(
本质上就是sequence_weighted_categorical_column，参见非序列的column命名

2022-02-28 05:52 UTC, tiankongdeguiji commented on easy_rec/python/feature_column/feature_column.py
> +    sub_feature_type = config.sub_feature_type
assert一下支持哪些sub_feature_type

2022-03-01 02:26 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +    sub_feature_type = config.sub_feature_type
已经改好了

2022-03-01 02:26 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +          wgt_fc = sequence_feature_column.sequence_numeric_column_with_weighted_categorical_column(
已经改好了。

2022-03-01 02:26 UTC, lgqfhwy commented on easy_rec/python/feature_column/feature_column.py
> +          tmp_id_col = sequence_feature_column.sequence_numeric_column_with_categorical_column_with_identity(
已经改好了。

2022-03-01 02:41 UTC, tiankongdeguiji approved these changes
LGTM

2022-03-02 02:48 UTC, chengmengli06 approved these changes

2022-03-02 02:48 UTC, chengmengli06 commented on easy_rec/python/utils/convert_rtp_fg.py
> +  if is_sequence:
add test cases for this piece of code.

2022-03-02 02:48 UTC, chengmengli06 commented on easy_rec/python/utils/config_util.py
> +      if feature_config.feature_type != feature_config.SequenceFeature:
what if it is SequenceFeature,  should it be sequence raw feature?

2022-03-02 03:32 UTC, merged