add vector retrieve
alibaba/EasyRec pull request #109
Opened 2022-01-15 03:36 UTC by yangxudong

vector retrieve

2022-01-15 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/EasyRec?pullRequest=109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/EasyRec?pullRequest=109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/EasyRec?pullRequest=109) it.</sub>

2022-01-16 06:28 UTC, chengmengli06 requested changes

2022-01-16 06:28 UTC, chengmengli06 commented on pai_jobs/easy_rec_flow_ex/easy_rec_ext.lua
> +  if cmd == "vector_retrieve" then
add an odps test @ https://github.com/alibaba/EasyRec/blob/master/easy_rec/python/test/odps_run.py

2022-01-16 06:28 UTC, chengmengli06 commented on pai_jobs/easy_rec_flow_ex/easy_rec_ext.lua
> +  if cmd == "vector_retrieve" then
resources file are here: https://github.com/alibaba/EasyRec/tree/master/samples/odps_script

2022-01-17 02:44 UTC, poson approved these changes

2022-02-17 11:21 UTC, yangxudong commented on pai_jobs/easy_rec_flow_ex/easy_rec_ext.lua
> +  if cmd == "vector_retrieve" then
> add an odps test @ https://github.com/alibaba/EasyRec/blob/master/easy_rec/python/test/odps_run.py

already added.

2022-02-18 03:22 UTC, chengmengli06 approved these changes

2022-02-19 05:46 UTC, merged