[feat]:support only sequence feature && fix neg sampler  bug for sequence feature
alibaba/EasyRec pull request #264
Opened 2022-08-04 09:48 UTC by lgqfhwy

2022-08-04 12:04 UTC, chengmengli06 requested changes

2022-08-04 12:04 UTC, chengmengli06 commented on easy_rec/python/layers/input_layer.py
> +                       only_sequence_feature=False):
what does this params mean?

2022-08-04 12:04 UTC, chengmengli06 commented on easy_rec/python/layers/input_layer.py
> +                       only_sequence_feature=False):
what does only_sequence_feature mean?

2022-08-04 12:04 UTC, chengmengli06 commented on easy_rec/python/layers/input_layer.py
> +  def target_attention(self,
it is better to refactor this code by move target_attention into a separate file named like:  target_attention_layer.py

2022-08-05 02:33 UTC, lgqfhwy commented on easy_rec/python/layers/input_layer.py
> +                       only_sequence_feature=False):
只返回过完 target_attention 之后的特征，不再和 key 进行 concat 了。

2022-08-05 02:33 UTC, lgqfhwy commented on easy_rec/python/layers/input_layer.py
> +                       only_sequence_feature=False):
同上。

2022-08-05 02:35 UTC, lgqfhwy commented on easy_rec/python/layers/input_layer.py
> +  def target_attention(self,
下一个 pr 这样搞，同时重构一下，然后还支持 key 和 hist_seq 不相等的情况。

2022-08-05 02:51 UTC, chengmengli06 commented on docs/source/feature/feature.rst
> +      only_sequence_feature:false
need_query_feature

2022-08-05 06:17 UTC, chengmengli06 approved these changes

2022-08-05 06:21 UTC, merged