[bugfix]:fix sequence feature last layer bug
alibaba/EasyRec pull request #283
Opened 2022-09-08 07:16 UTC by lgqfhwy

2022-09-08 07:41 UTC, tiankongdeguiji requested changes

2022-09-08 07:41 UTC, tiankongdeguiji commented on easy_rec/python/layers/dnn.py
>              name='%s/dnn_%d/bn' % (self._name, i))
bn一般最后一层也是没有的

2022-09-08 07:41 UTC, tiankongdeguiji commented on easy_rec/python/layers/sequence_feature_layer.py
> +        tf.tile(neg_feature[tf.newaxis, :, :], multiples=[1, neg_num, 1])
dim-0 shape不match

2022-09-13 02:40 UTC, lgqfhwy commented on easy_rec/python/layers/dnn.py
>              name='%s/dnn_%d/bn' % (self._name, i))
已修改。

2022-09-13 02:40 UTC, lgqfhwy commented on easy_rec/python/layers/sequence_feature_layer.py
> +        tf.tile(neg_feature[tf.newaxis, :, :], multiples=[1, neg_num, 1])
已修改。

2022-09-13 06:06 UTC, tiankongdeguiji requested changes

2022-09-13 06:06 UTC, tiankongdeguiji commented on easy_rec/python/layers/sequence_feature_layer.py
> +        None,
why l2_reg is None?

2022-09-13 06:09 UTC, tiankongdeguiji requested changes

2022-09-13 06:09 UTC, tiankongdeguiji commented on easy_rec/python/model/multi_tower_din.py
> +        last_layer_no_activation=True)
last_layer_no_batch_norm=True

2022-09-13 10:44 UTC, lgqfhwy commented on easy_rec/python/layers/sequence_feature_layer.py
> +        None,
已修改。

2022-09-13 10:45 UTC, lgqfhwy commented on easy_rec/python/model/multi_tower_din.py
> +        last_layer_no_activation=True)
已修改。

2022-09-15 03:26 UTC, tiankongdeguiji approved these changes

2022-09-15 03:29 UTC, merged