Bug fix of SENet when run with MirroredStrategy
alibaba/EasyRec pull request #443
Opened 2023-12-25 12:10 UTC by yangxudong

2023-12-26 01:34 UTC, chengmengli06 requested changes

2023-12-26 01:34 UTC, chengmengli06 commented on easy_rec/python/layers/keras/fibinet.py
> +    initializer = tf.keras.initializers.VarianceScaling()
add a test case

2023-12-26 03:11 UTC, yangxudong commented on easy_rec/python/layers/keras/fibinet.py
> +    initializer = tf.keras.initializers.VarianceScaling()
there already has one: mmoe_backbone_on_taobao.config

2023-12-28 06:54 UTC, lgqfhwy approved these changes

2023-12-28 12:01 UTC, chengmengli06 approved these changes

2023-12-28 12:03 UTC, merged