fix update_config_remove_invalid_subseq_feature
alibaba/EasyRec pull request #475
Opened 2024-07-05 08:58 UTC by chengaofei

fix update_config_remove_invalid_subseq_feature

2024-07-05 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/EasyRec?pullRequest=475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/EasyRec?pullRequest=475) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/EasyRec?pullRequest=475) it.</sub>

2024-07-05 08:59 UTC, chengaofei commented
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

2024-07-08 02:24 UTC, tiankongdeguiji requested changes

2024-07-09 01:36 UTC, chengaofei commented on easy_rec/python/tools/add_feature_info_to_config.py
> +            hist_seq = hist_seq.split('seq__')[1]
the judgment criteria have been deleted

2024-07-09 01:40 UTC, tiankongdeguiji approved these changes

2024-07-09 06:09 UTC, merged