fix default value bug in inference and make FG type compatible with E…
alibaba/EasyRec pull request #66
Opened 2021-10-28 09:02 UTC by dawn310826

…asyRec input_type

2021-11-11 09:18 UTC, lgqfhwy approved these changes

2021-11-11 09:31 UTC, tiankongdeguiji requested changes

2021-11-11 09:31 UTC, tiankongdeguiji commented on easy_rec/python/inference/predictor.py
> +    input_fields_info = {
input_fields_info -> effective_fields_info

2021-11-11 09:31 UTC, tiankongdeguiji commented on easy_rec/python/inference/predictor.py
> +    ]
do not need select all cols.

2021-11-11 09:31 UTC, tiankongdeguiji commented on easy_rec/python/utils/input_utils.py
> +def string_to_number(record_default, cur_field, name=''):
make input params same as tf.string_to_number

2021-11-11 09:31 UTC, tiankongdeguiji commented on easy_rec/python/utils/input_utils.py
> +def string_to_number(record_default, cur_field, name=''):
add docstring

2021-11-11 09:31 UTC, tiankongdeguiji commented on easy_rec/python/utils/input_utils.py
> +    tmp_field = tf.string_to_number(
add comment `deal with scientific notation`

2021-11-11 09:31 UTC, tiankongdeguiji commented on easy_rec/python/test/fg_test.py
> +  def test_fg_dtype(self):
put the test into train_eval_test

2021-11-11 12:26 UTC, dawn310826 commented on easy_rec/python/test/fg_test.py
> +  def test_fg_dtype(self):
done

2021-11-11 12:26 UTC, dawn310826 commented on easy_rec/python/utils/input_utils.py
> +    tmp_field = tf.string_to_number(
done

2021-11-11 12:26 UTC, dawn310826 commented on easy_rec/python/utils/input_utils.py
> +def string_to_number(record_default, cur_field, name=''):
done

2021-11-11 12:26 UTC, dawn310826 commented on easy_rec/python/inference/predictor.py
> +    ]
done

2021-11-12 06:33 UTC, tiankongdeguiji approved these changes
LGTM

2021-11-12 11:40 UTC, merged